[package]
name = "deadnews-template-rust"
version = "0.1.2"
edition = "2021"
description = "Rust Project Template"
repository = "https://github.com/DeadNews/deadnews-template-rust"
license = "MIT"
keywords = ["template", "sample"]

[dependencies]
actix-web = "4.5.1"
env_logger = "0.11.1"
log = "0.4.20"
