[package]
name = "deadnews-template-rust"
version = "0.1.0"
edition = "2021"
description = "Rust Project Template"
repository = "https://github.com/DeadNews/deadnews-template-rust"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pyo3 = { version = "0.19.2", features = [
    "abi3-py37",
    "extension-module",
    "multiple-pymethods",
] }
