services:
  template-rust:
    build:
      context: .
      args:
        PROFILE: dev-build
    healthcheck:
      test: [CMD, /bin/httpcheck, http://127.0.0.1:8000/health]
      interval: 1m
      retries: 3
      timeout: 10s
      start_period: 1m
    environment:
      SERVICE_DSN: postgres://postgres:postgres@postgres:5432/postgres
      RUST_LOG: deadnews_template_rust=info,tower_http=debug
    ports:
      - 127.0.0.1:8000:8000/tcp

  postgres:
    image: postgres:18-alpine
    healthcheck:
      test: [CMD, pg_isready, -U, postgres]
      interval: 1m
      retries: 3
      timeout: 10s
      start_period: 1m
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
