name: Security audit

on:
  push:
    paths:
      - "**/Cargo.toml"
      - "**/Cargo.lock"
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  cargo-deny:
    name: Check deps
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check deps
        uses: embarkstudios/cargo-deny-action@4de59db63a066737e557c2c4dd3d1f70206de781 # v2.0.10
        with:
          command: check bans sources
