name: Security audit

on:
  push:
    paths:
      - "**/Cargo.toml"
      - "**/Cargo.lock"
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  cargo-deny:
    name: Check deps
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check deps
        uses: embarkstudios/cargo-deny-action@34899fc7ba81ca6268d5947a7a16b4649013fea1 # v2.0.11
        with:
          command: check bans sources
