name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@1482605bfc5719782e1267fd0c0cc350fe7646b8 # v1
        with:
          toolchain: stable

      - name: Rust Cache
        uses: swatinem/rust-cache@a22603398250b864f7190077025cf752307154dc # v2.7.2

      - name: Run tests
        run: make test

  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@1482605bfc5719782e1267fd0c0cc350fe7646b8 # v1
        with:
          toolchain: stable
          components: rustfmt

      - name: Rust Cache
        uses: swatinem/rust-cache@a22603398250b864f7190077025cf752307154dc # v2.7.2

      - name: Check formatting
        run: make fmt

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@1482605bfc5719782e1267fd0c0cc350fe7646b8 # v1
        with:
          toolchain: stable
          components: clippy

      - name: Rust Cache
        uses: swatinem/rust-cache@a22603398250b864f7190077025cf752307154dc # v2.7.2

      - name: Clippy check
        run: make clippy

  docs:
    name: Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@1482605bfc5719782e1267fd0c0cc350fe7646b8 # v1
        with:
          toolchain: stable

      - name: Rust Cache
        uses: swatinem/rust-cache@a22603398250b864f7190077025cf752307154dc # v2.7.2

      - name: Check documentation
        run: make doc
        env:
          RUSTDOCFLAGS: -D warnings
