name: Docker

on:
  push:
    tags: ["v*.*.*"]
  pull_request:
    paths:
      - "Dockerfile*"

permissions:
  contents: read
  id-token: write
  packages: write
  security-events: write

jobs:
  docker:
    name: Docker
    uses: deadnews/deadnews-template-docker/.github/workflows/docker-reusable.yml@main

  docker-static:
    name: Docker Static
    uses: deadnews/deadnews-template-docker/.github/workflows/docker-reusable.yml@main
    with:
      dockerfile: Dockerfile.static
      flavor: |
        suffix=-static,onlatest=true
